# scrutinizer-ci.com configuration
imports:
    - javascript
    - python
filter:
    excluded_paths: [docs/*, weblate/trans/south_migrations/*, weblate/accounts/south_migrations/*, weblate/lang/south_migrations/*]
