checks:
    python:
        code_rating: true
        duplicate_code: true
        classes_valid_slots: true
filter:
    excluded_paths:
        - '*/migrations/*'
tools:
    pylint:
        python_version: '3'
        config_file: '.pylintrc'
build:
    environment:
        python: 3.6
        postgresql: true
    dependencies:
        override:
            - pip install -r ci/requirements-scrutinizer.txt
    nodes:
        analysis:
            tests:
                override:
                  - sed -i 's/pylint_django//' .pylintrc
                  - 
                    command: pylint-run --rcfile=.pylintrc
                    idle_timeout: 360
                  - py-scrutinizer-run
        tests:
            tests:
                override:
                    -
                        command: export DJANGO_SETTINGS_MODULE=weblate.settings_test
                    -
                        command: ./manage.py collectstatic --noinput
                    -
                        command: coverage run --source . ./manage.py test
                    -
                        command: coverage combine
                        coverage:
                            file: .coverage
                            format: py-cc
