checks:
    python:
        code_rating: true
        duplicate_code: true
tools:
    pylint:
        python_version: '2'
        config_file: 'ci/pylint-scrutinizer.rc'
filter:
    excluded_paths:
        - '*/test/*'
        - '*/migrations/*'
before_commands:
    - pip install Django
build:
    dependencies:
        before:
            - pip install https://github.com/translate/translate/zipball/de3f080abf6f2fecfca97d283a58eb6824d8078e
            - pip install Django Whoosh lxml Pillow six python-dateutil python-social-auth django-crispy-forms oauthlib django_compressor coverage chardet
        override:
            - true
    tests:
        override:
            -
                command: coverage run --source . ./manage.py test --settings=weblate.settings_test
                coverage:
                    file: .coverage
                    format: py-cc
