checks:
    python:
        code_rating: true
        duplicate_code: true
tools:
    pylint:
        python_version: '3'
        config_file: 'ci/pylint-scrutinizer.rc'
filter:
    excluded_paths:
        - '*/migrations/*'
before_commands:
    - sudo pip3 install ci/requirements-scrutinizer.txt
build:
    environment:
        python: 3.6
        postgresql: true
    dependencies:
        override:
            - pip install -r ci/requirements-scrutinizer.txt
    tests:
        override:
            -
                command: export DJANGO_SETTINGS_MODULE=weblate.settings_test
            -
                command: ./manage.py collectstatic --noinput
            -
                command: coverage run --source . ./manage.py test
            -
                command: coverage combine
                coverage:
                    file: .coverage
                    format: py-cc
    nodes:
        analysis:
            tests:
                override:
                  - py-scrutinizer-run
