language: python
python:
  - "2.7"
# - Test against all supported Django versions with sqlite
# - Test against all supported databases with current Django
# - Run Selenium tests on current Django
# - Run pylint/pep8 checker
env:
  matrix:
    - CI_DJANGO="Django>=1.6,<1.7" CI_LINT=1
    - CI_DJANGO="Django>=1.7,<1.8" CI_LINT=1
    - CI_DJANGO="Django>=1.7,<1.8" CI_DATABASE=mysql
    - CI_DJANGO="Django>=1.7,<1.8" CI_DATABASE=postgresql
    - CI_DJANGO="Django>=1.7,<1.8"
    - CI_DJANGO="Django>=1.6,<1.7"
    - CI_DJANGO="Django>=1.7,<1.8" CI_DATABASE=mysql CI_RUN_TESTS="-p test_selenium.py" CI_SELENIUM=1
  global:
    - DJANGO_SETTINGS_MODULE=weblate.settings_test
    - CI_REQUIREMENTS=travis
before_install:
  - git clone --depth 1 --branch v0.1.2 https://github.com/ruleant/buildtime-trend.git $HOME/buildtime-trend 
  - source $HOME/buildtime-trend/init.sh
  - timestamp.sh packages
  - sudo apt-get update -qq
  - sudo apt-get install git libicu-dev
# commands to install dependencies
install:
  - timestamp.sh install
  - ./ci/install
  - pip install -r ${BUILD_TREND_HOME}/requirements.txt
# create databases
before_script:
  - timestamp.sh before_script
  - ./ci/setup-env
  - echo -e "[server]\nmax_allowed_packet=64M\nwait_timeout=28800" | sudo tee -a /etc/mysql/conf.d/weblate.cnf
  - sudo service mysql restart
# commands to run tests
script:
  - timestamp.sh tests
  - if [ -z "$CI_LINT" ] ; then ./ci/run-test ; else ./ci/run-lint ; fi
after_script:
  - timestamp.sh coveralls
  - if [ -z "$CI_LINT" ] ; then coveralls ; fi
  - if [ -z "$CI_LINT" ] ; then ocular --data-file ".coverage" --config-file ".coveragerc" ; fi
  - timestamp.sh done
  - sync-buildtime-trend-with-gh-pages.sh
cache:
  apt: true
  directories:
    - $HOME/.pip-cache/
matrix:
  allow_failures:
    - python: "2.7"
      env: CI_DJANGO="Django>=1.7,<1.8" CI_LINT=1
