language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4.6 DATABASE=mysql
  - DJANGO_VERSION=1.4.6 DATABASE=postgresql
  - DJANGO_VERSION=1.4.6 DATABASE=sqlite
  - DJANGO_VERSION=1.5.2 DATABASE=mysql
  - DJANGO_VERSION=1.5.2 DATABASE=postgresql
  - DJANGO_VERSION=1.5.2 DATABASE=sqlite
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.4.5 DATABASE=mysql
    - python: "2.6"
      env: DJANGO_VERSION=1.4.5 DATABASE=postgresql
    - python: "2.6"
      env: DJANGO_VERSION=1.5.1 DATABASE=mysql
    - python: "2.6"
      env: DJANGO_VERSION=1.5.1 DATABASE=postgresql
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install git libffi-dev libpq-dev libmysqlclient-dev libicu-dev
# commands to install dependencies
install: 
  - pip install --use-mirrors Django==$DJANGO_VERSION
  - pip install --use-mirrors -r requirements.txt
  - pip install --use-mirrors -r requirements-optional.txt
  - pip install --use-mirrors -r requirements-test.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors -r requirements-2.6.txt ; fi
# generate configuration and create databases
before_script:
  - cp weblate/settings_example.py weblate/settings.py
  - mysql -e 'create database weblate;'
  - psql -c 'create database weblate;' -U postgres
# commands to run tests
script: 
  - ./scripts/generate-locales
  - ./manage.py validate --settings weblate.settings_test_$DATABASE
  - ./manage.py syncdb --noinput --settings weblate.settings_test_$DATABASE
  - ./manage.py migrate --settings weblate.settings_test_$DATABASE
  - coverage run --source=. ./manage.py test --settings weblate.settings_test_$DATABASE trans lang accounts
  - pep8 --exclude migrations accounts trans lang
  - pylint --reports=n --rcfile=pylint.rc trans accounts weblate lang
after_success:
  - coveralls
notifications:
  irc:
    channels: "irc.freenode.org#weblate"
    on_success: change
    on_failure: change
