#
# Weblate testsuite for Travis-CI
#
# - Test against all supported Django versions with sqlite
# - Test against all supported databases with current Django
# - Run Selenium tests on current Django
# - Test setup.py
#
language: python
python:
  - "2.7"
# build matrix configuration
env:
  matrix:
    - CI_PIP_DEPS="Django>=1.10,<1.11"
    - CI_PIP_DEPS="Django>=1.10,<1.11" CI_MODE=setup
    - CI_PIP_DEPS="Django>=1.10,<1.11" CI_DATABASE=mysql
    - CI_PIP_DEPS="Django>=1.10,<1.11" CI_DATABASE=postgresql
    - CI_PIP_DEPS="Django>=1.9,<1.10"
    - CI_PIP_DEPS="Django>=1.10,<1.11" CI_DATABASE=postgresql CI_MODE=selenium
    - CI_PIP_DEPS="Sphinx" CI_MODE=docs
  global:
    - DJANGO_SETTINGS_MODULE=weblate.settings_test
    - CI_REQUIREMENTS=travis
    - CI_MODE=test
# commands to install dependencies
install:
  - ./ci/install
# create databases
before_script:
  - ./ci/setup-env
# commands to run tests
script:
  - ./ci/run-$CI_MODE
# upload coverage
after_script:
  - ./ci/report-coverage
# use docker based faster build
sudo: false
# trigger Buildtime Trend Service to parse Travis CI log
notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
matrix:
  include:
    - python: "3.5"
      env: CI_PIP_DEPS="Django>=1.10,<1.11"
addons:
  apt:
    packages:
    - mercurial
    - libgettextpo0
    - git-svn
cache:
  - pip
  - ccache
