#
# Weblate testsuite for Travis-CI
#
# - Test against all supported Django versions with sqlite
# - Test against all supported databases with current Django
# - Run Selenium tests on current Django
# - Test setup.py
#
language: python
python:
  - "2.7"
# build matrix configuration
env:
  matrix:
    - CI_PIP_DEPS="Django>=1.10,<1.11"
    - CI_PIP_DEPS="Django>=1.10,<1.11" CI_MODE=setup
    - CI_PIP_DEPS="Django>=1.10,<1.11" CI_DATABASE=mysql
    - CI_PIP_DEPS="Django>=1.10,<1.11" CI_DATABASE=postgresql
    - CI_PIP_DEPS="Django>=1.10,<1.11" CI_DATABASE=postgresql CI_MODE=selenium
    - CI_PIP_DEPS="--pre Django"
    - CI_PIP_DEPS="sphinxcontrib-httpdomain docutils!=0.13.1" CI_MODE=docs
  global:
    - DJANGO_SETTINGS_MODULE=weblate.settings_test
    - CI_REQUIREMENTS=travis
    - CI_MODE=test
# commands to install dependencies
install:
  - export TESSERACT_INSTALL=`pwd`/.tesseract
  - export TESSERACT_PKG=$TESSERACT_INSTALL/lib/pkgconfig
  - mkdir -p $TESSERACT_INSTALL
  - export LD_LIBRARY_PATH=$TESSERACT_INSTALL/lib:$LD_LIBRARY_PATH
  - export PKG_CONFIG_PATH=$TESSERACT_PKG:$PKG_CONFIG_PATH
  - export TESSDATA_PREFIX=/usr/share/tesseract-ocr/tessdata/
  - ./ci/install
# create databases
before_script:
  - ./ci/setup-env
  - ./manage.py list_versions
# commands to run tests
script:
  - ./ci/run-$CI_MODE
# upload coverage
after_script:
  - ./ci/report-coverage
# use docker based faster build
sudo: false
# trigger Buildtime Trend Service to parse Travis CI log
notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
matrix:
  include:
    - python: "3.5"
      env: CI_PIP_DEPS="Django>=1.10,<1.11"
  allow_failures:
    - python: "2.7"
      env: CI_PIP_DEPS="--pre Django"
addons:
  apt:
    packages:
    - git-svn
    - graphviz
    - tesseract-ocr
cache:
  pip: true
  ccache: true
  directories:
    - .tesseract
deploy:
  provider: bintray
  file: bintray.json
  user: nijel
