comment:
  layout: header, changes, diff, sunburst
coverage:
  ignore:
  - openshift/.*
  - .*/openshift/.*
  - .*/settings_.*.py
  - .*/settings.py
  - .*/wsgi.py
  status:
    patch: false
    project:
      default:
        target: '90'
